[pytest]
pythonpath = .
testpaths = tests
addopts =
    --alluredir=./reports/allure-results
    --clean-alluredir
    --html=./reports/report.html
    --self-contained-html
    --log-file=./reports/logs/pytest.log
    --log-level=INFO
    -v

log_cli_format = %(asctime)s - %(name)s - %(levelname)s - %(message)s
log_cli_date_format = %Y-%m-%d %H:%M:%S

markers =
    slow: marks tests as slow
    ui: marks tests as UI tests
    api: marks tests as API tests
    e2e: marks tests as end-to-end tests